services:
  gpu:
    container_name: uv_docker_gpu
    build:
      context: .
      dockerfile: docker/Dockerfile.gpu
    image: uv_docker_gpu
    shm_size: '32gb'
    volumes:
      - type: bind
        source: $PWD
        target: /workspace
      - type: volume
        source: venv
        target: /workspace/.venv
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    tty: true

  mac:
    container_name: uv_docker_mac
    build:
      context: .
      dockerfile: docker/Dockerfile.mac
    image: uv_docker_mac
    shm_size: '16gb'
    volumes:
      - type: bind
        source: $PWD
        target: /workspace
        consistency: delegated
      - type: volume
        source: venv
        target: /workspace/.venv
    working_dir: /workspace
    tty: true

volumes:
  venv:
